# Site settings
title: Joshua Hull's Resume
description: Joshua Hull's Resume
favicon: /assets/img/avatar.JPG
baseurl: https://joshua-hull.github.io/resumecard
url: https://joshua-hull.github.io/resumecard
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Joshua Hull
  title: Software Developer
  address: Greenville, SC
  email: joshua.thorild.hull[at]gmail[dot]com
  link: http://joshua-hull.github.io
  weibo:
  github: joshua-hull
  linkedin:
  twitter:
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Care Coordination Institute
      location: Greenville, SC
      title: Software Engineer
      started: 2016
      duration: (May 2016 - Present)
      description:
    - work2:
      company: Website Pipeline
      location: Greenville, SC
      title: Software Engineer
      started: 2015
      duration: (January 2015 - March 2016)
      description:
    - work3:
      company: Clemson University School of Computing
      location: Clemson, SC
      title: Teaching Assistant
      started: 2014
      duration: (August 2014 - December 2014)
      description:
    - work4:
      company: Clemson University Department of Mathematical Sciences
      location: Clemson, SC
      title: Mobile Application Developer
      started: 2014
      duration: (May 2014 - July 2014)
      description:
    - work5:
      company: Clemson University Computing and Information Technology
      location: Clemson, SC
      title: Mobile Application Developer
      started: 2014
      duration: (January 2014 - May 2014)
      description:
  educationHistory:
    - education1:
      organization: Clemson University
      location: Clemson, SC
      degree: Bachelor
      major: Computer Science
      started: 2012
      duration: (2012 - 2014)
      description:
  # languages:
  #   - language1:
  #     name: English
  #     proficiency: Native
  programmingSkills:
    - skill1:
      name: C/C++
      percentage:
    - skill2:
      name: Objective-C
      percentage:
    - skill3:
      name: HTML5/CSS3
      percentage:
    - skill4:
      name: JavaScript
      percentage:
    - skill5:
      name: .NET
      percentage:
    - skill6:
      name: ASP
      percentage:
  enviornments:
    - enviornment1:
    name: iOS
    percentage:
    - enviornment2:
    name: Linux
    percentage:
    - enviornment3:
    name: AWS
    percentage:
    - enviornment4:
    name: .NET
    percentage:
  databases:
    - database1:
    name: MySQL
    percentage:
    - database2:
    name: SQLite
    percentage:
    - database3:
    name: PostgreSQL
    percentage:
    - database4:
    name: T-SQL
    percentage:
  awards:
    - award1:
    name: EPA P3 Awards
    desc: Honorable Mentions
    date: 2014
    - award2:
    name: Deans's List
    desc:
    date: Fall 2012
    - award3:
    name: Dean's List
    desc:
    date: Spring 2013
  publications:
