# Site settings
title: Joshua Hull's Resume
description: Joshua Hull's Resume
favicon: /assets/img/avatar.JPG
baseurl: https://joshua-hull.github.io/resumecard
url: https://joshua-hull.github.io/resumecard
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Joshua Hull
  title: Software Developer
  address: Greenville, SC
  email: joshua.thorild.hull@gmail.com
  link: http://joshua-hull.github.io
  weibo:
  github: joshua-hull
  linkedin:
  twitter:
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Care Coordination Institute
      location: Greenville, SC
      title: Software Engineer
      started: 2016
      duration: (May 2016 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Clemson University
      location: Clemson, SC
      degree: Bachelor
      major: Computer Science
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  # languages:
  #   - language1:
  #     name: English
  #     proficiency: Native
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
